### ISSUE TITLE
Cannot find module 'fast-glob'

### ISSUE THREAD

**Issue by felipeqq2** [bartholomej/svelte-sitemap#5]
Apparently, there is something wrong with the `fast-glob` dependency that throws this error when running the postbuild script. I'm using pnpm, so my node_modules folder is flat. I _think_ that's because `fast-glob` is a devDependency, instead of a normal dependency, but idk

<details>
<summary>Logs</summary>

```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'fast-glob'
Require stack:
- C:\Users\user\svelte\node_modules\.pnpm\svelte-sitemap@1.2.1\node_modules\svelte-sitemap\src\helpers\global.helper.js
- C:\Users\user\svelte\node_modules\.pnpm\svelte-sitemap@1.2.1\node_modules\svelte-sitemap\src\index.js
- C:\Users\user\svelte\node_modules\.pnpm\svelte-sitemap@1.2.1\node_modules\svelte-sitemap\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Users\user\svelte\node_modules\.pnpm\svelte-sitemap@1.2.1\node_modules\svelte-sitemap\src\helpers\global.helper.js:7:37)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\user\\svelte\\node_modules\\.pnpm\\svelte-sitemap@1.2.1\\node_modules\\svelte-sitemap\\src\\helpers\\global.helper.js',
    'C:\\Users\\user\\svelte\\node_modules\\.pnpm\\svelte-sitemap@1.2.1\\node_modules\\svelte-sitemap\\src\\index.js',
    'C:\\Users\\user\\svelte\\node_modules\\.pnpm\\svelte-sitemap@1.2.1\\node_modules\\svelte-sitemap\\index.js'
  ]
}
```

</details>

**Comment by bartholomej** [comment]
I see!
So `next` version is for you @felipeqq2 ;)

Can you try `1.3.0-beta.0`?
```bash
pnpm i svelte-sitemap@next --save-dev
```

Let me know how it works?

**Comment by felipeqq2** [comment]
It works as expected now!

**Comment by bartholomej** [comment]
@felipeqq2 Great!

So stable version [v1.3.0](https://github.com/bartholomej/svelte-sitemap/releases/tag/) has been released just now ;)

Thanks ;))
